### ISSUE TITLE
CRITICAL: All single site options suddenly synced

### ISSUE THREAD

**Issue by frizzant** [owlwatch/acf-multisite-options#13]
It seems that this plugin syncs all single sites options - so basically breaking the functionality of non network ACF options.
When i change options of site example.com it syncs those to the options of example2.com, example3.com etc.
The network settings themselves seem to work as expected.

**Comment by fabrizim** [comment]
Hi @frizzant  - I just updated the code with what I'm using on a production site. Can you try to update and see if that fixes the issue?

**Comment by frizzant** [comment]
I cloned the new git@github.com:owlwatch/acf-multisite-options.git and activated it on our multisite. The issue is still in existence. Each subsite just overrides the page options of site "x".
I'm not sure where in the code you are differentiating the sites from eachother.
